Merged PR 136: PR 134 from UC1 repo: adapt to template repo
Steps:
- [X] Clone this repo into your computer
- [X] Checkout this branch (uc1-smoketest-....)
- [X] Delete the parts that are related to the use case
- [X] Commit your changes
- [X] Publish the PR

diff --git a/azure-pipelines/templates/deploy-model.template.yml b/azure-pipelines/templates/deploy-model.template.yml
--- a/azure-pipelines/templates/deploy-model.template.yml
+++ b/azure-pipelines/templates/deploy-model.template.yml
@@ -6,36 +6,45 @@
 parameters:
 - name: environment
   type: string
+- name: serviceConnection
+  type: string
+- name: resourceGroup
+  type: string
+- name: amlWorkspace
+  type: string
 - name: deploymentType
   type: string
 - name: webserviceName
   type: string
+- name: deleteAfterwards
+  type: string
+  default: false
 
 
 jobs:
 
-- job: check_aks
-  displayName: 'AKS Check'
-  steps:
-    - bash: |
-        if [ "${{parameters.deploymentType}}" != "aks" ]; then
-          echo "Not AKS deployment. Skipping check."
-        elif [ "$(AKS_COMPUTE)" == "" ]; then
-          >&2 echo "Error: variable AKS_COMPUTE must be set for AKS deployments"
-        fi
-      displayName: 'Check AKS_COMPUTE variable'
-      failOnStderr: true
+- ${{ if eq(parameters.deploymentType, 'aks') }}:
+  - job: check_aks
+    displayName: 'AKS Check'
+    steps:
+      - bash: |
+          if [ "$(AKS_COMPUTE)" == "" ]; then
+            >&2 echo "Error: variable AKS_COMPUTE must be set for AKS deployments"
+          fi
+        displayName: 'Check AKS_COMPUTE variable'
+        failOnStderr: true
 
 - job: deploy_model
   displayName: 'Deploy Model'
-  dependsOn: check_aks
+  ${{ if eq(parameters.deploymentType, 'aks') }}:
+    dependsOn: check_aks
   timeoutInMinutes: 0
   steps:
   - template: utils/run-aml-python-code.template.yml
     parameters:
-      serviceConnection: $(DEV_SERVICECONNECTION_WS)
-      resourceGroup: $(DEV_RESOURCE_GROUP)
-      amlWorkspace: $(DEV_AMLWORKSPACE)
+      serviceConnection: ${{parameters.serviceConnection}}
+      resourceGroup: ${{parameters.resourceGroup}}
+      amlWorkspace: ${{parameters.amlWorkspace}}
       scriptPath: operation/execution/model_deployment.py
       scriptArguments: |
         --model-name $(AML_MODEL_NAME) \
@@ -44,7 +53,35 @@ jobs:
         --aks-target-name $(AKS_COMPUTE)
       scriptExtraDependencies: pyyaml
 
-# - job: smoke_test
-#   displayName: 'Test Webservice'
-#   dependsOn: deploy_model
-#   steps: #TODO
+- job: smoke_test
+  displayName: 'Test Webservice'
+  dependsOn: deploy_model
+  steps:
+  - template: utils/run-aml-python-code.template.yml
+    parameters:
+      serviceConnection: ${{parameters.serviceConnection}}
+      resourceGroup: ${{parameters.resourceGroup}}
+      amlWorkspace: ${{parameters.amlWorkspace}}
+      scriptPath: operation/execution/smoke_test_webservice.py
+      scriptArguments: --webservice-name ${{parameters.webserviceName}}
+      scriptExtraDependencies: pyyaml requests
+
+- ${{ if eq(parameters.deleteAfterwards, 'true') }}:
+  - job: delete_webservice
+    displayName: 'Delete Webservice'
+    dependsOn: smoke_test
+    steps:
+    - task: AzureCLI@1
+      name: delete_webservice
+      displayName: 'Delete Webservice'
+      inputs:
+        azureSubscription: ${{parameters.serviceConnection}}
+        scriptLocation: inlineScript
+        inlineScript: |
+          # Install ML extension
+          az extension add -n azure-cli-ml
+          # Delete webservice
+          az ml service delete --name ${{parameters.webserviceName}} \
+                              --workspace-name ${{parameters.amlWorkspace}} \
+                              --resource-group ${{parameters.resourceGroup}}
+        failOnStandardError: true
